source 'https://github.com/CocoaPods/Specs.git'
source 'git@bitbucket.org:cybavo/pw_podspecs.git'

target 'programmable-wallet-sdk-ios-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'PWSDK_TEST'

end
