source 'https://github.com/CocoaPods/Specs.git'
source 'git@bitbucket.org:cybavo/pw_podspecs.git'

target 'programmable-wallet-sdk-ios-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  
  pod 'CircleProgrammableWalletSDK_Internal', '1.0.15'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

      # See this: https://developer.apple.com/forums/thread/725300
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
